#!/bin/bash
# Script to create simple menus and take action according to that selected
# menu item

libdir=$HOME/scripts/Sorlanet-Tech/2.1gen

if [[ -f $libdir ]] ; then
. $libdir
fi

first=109; second=163; third=50; fourth=1
A="1"; B="a"; C="6"; D="0"; E="3"; F="0"; G="1"; H="0"; I="8"; J="2"; K="2"; L="0"; M="2"; N="0"; O="a"; P="2"

_one_one()
{
echo -e "using $first.$second.$third"
}

_initial()
{
echo -e "-------------------------------------"
echo -e " Main Menu "
echo -e "-------------------------------------"
echo -e "[1] Configure IPv4"
echo -e "[2] Configure IPv6"
echo -e "[3] set NameServer"
echo -e "[4] Paste configs"
echo -e "======================="
echo -e -n "Enter your menu choice [1-5]: "
}

_ipv4_conf() {
echo -e "-------------------------------------"
echo -e " IPv4 conf, current addr is $first.$second.$third.$fourth"
echo -e "-------------------------------------"
echo -e "[1] Use current"
echo -e "[2] Configure a new"
echo -e "[5] Exit/Stop"
echo -e "======================="
echo -e -n "Enter your menu choice [1-5]: "
echo -e "Config happens in four stages, in the first stage type eg.\n{192}[ENTER], this logs the first bit of the adress\nContinue four times"
read first && echo -e "\c"; read second ; read third ; read fourth;
echo -e "you input $first.$second.$third.$fourth"
}

_one()
{
echo -e "-------------------------------------"
echo -e " IPv4 conf, current addr is $first.$second.$third.$fourth"
echo -e "-------------------------------------"
echo -e "[1] Use current"
echo -e "[2] Configure a new"
echo -e "[5] Exit/Stop"
echo -e "======================="
echo -e -n "Enter your menu choice [1-5]: "
}

_two()
{
echo -e "-------------------------------------"
echo -e " IPv6 conf, current addr is ${P}${O}${N}${M}:${L}${K}${J}${I}:${H}${G}${F}${E}:${D}${C}${B}${A}"
echo -e "-------------------------------------"
echo -e "[1] Use current"
echo -e "[2] Configure a new"
echo -e "[5] Exit/Stop"
echo -e "======================="
echo -e -n "Enter your menu choice [1-5]: "

}

_two_one()
{
echo -e "-------------------------------------"
echo -e "[IPv6] [R]ange of the addr, the range of its [S]pan will be shown under"
echo -e "-------------------------------------"
echo -e "[S] from ::b010 it increments to ::b180, with variations like ${leet} ${cake} ${babe}"
echo -e "[D] configure first 12 digits, (these need not be incremented as the last 4 are plenty)"
echo -e "[E] Exit/Stop"
echo -e "[R] Keep current range "
echo -e "-------------------------------------"
echo -e "\n\n\n\n[ current - ${P}${O}${N}${M}:${L}${K}${J}${I}:${H}${G}${F}${E}:${D}${C}${B}${A} ]\n\
[ NS1_v6 - $NS1_v6]\n\
[ NS2_v6 - $NS2_v6]"
echo -e -n "Enter your menu choice [S]: "
echo -e "using :::"
}

while :
	 do
		clear
		# first menu
		_initial
			read menuchoice
			case $menuchoice in
			1) 
			_one
			read ipv4
			case $ipv4 in
			1) 
_one_one
;;
2|two) 
_one_two
;;
3) 
_one_three
exit 0
;;
esac
;;
 2)
clear
_two
read ipv6
case $ipv6 in
1) 
# use current, which means we just wanna return to last menu,
return
_two_one
;;
2|two) 
_two_two
echo -e "Config happens in 16 stages, in the first stage type eg.\n{2}[ENTER], this logs the first bit of the adress\nContinue 16 times"
read P; read O; read N; read M; read L; read K; read J; read I; read H; read G; read F; read E; read D; read C; read B; read A;
echo -e "you input ${P}${O}${N}${M}:${L}${K}${J}${I}:${H}${G}${F}${E}:${D}${C}${B}${A}"
;;
5) exit 0;;
esac
;;
  3)
_three
echo -e "magic injected"
;;
  4)
_four
echo -e "Nothing done"
;; 
 esac
done
